ConsultarYoutubeAPI/Models/ErrorViewModel.cs
using System;

namespace ConsultarYoutubeAPI.Models
{
  public class ErrorViewModel
  {
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
  }
}

ConsultarYoutubeAPI/Controllers/CanalController.cs
using Common.Youtube;

using Dommain.Entidades.CanalHost;
using Dommain.Entidades.Comum;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using Repository;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ConsultarYoutubeAPI.Controllers
{
  public class CanalController : Controller
  {
    private readonly IYoutubeAccesAPI _youtubeAccesAPI;
    private readonly Context _Context;

    public CanalController(IYoutubeAccesAPI youtubeAccesAPI, Context pContext)
    {
      _youtubeAccesAPI = youtubeAccesAPI;
      _Context = pContext;
    }
    // GET: CanalController
    [HttpGet]
    public ActionResult Index()
    {
      return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Index(ConsultaCanal pCanal)
    {
      try
      {
        if (ModelState.IsValid)
        {
          var canalBD = (from c in _Context.Set<ConsultaCanal>()
                         join root in _Context.Set<CanalRoot>()
                         on c.CanalRootID equals root.ID                                                
                         select new ConsultaCanal()
                         {
                           ID = c.ID,
                           TermoConsulta = c.TermoConsulta,
                           CanalRootID = c.CanalRootID,
                           CanalRoot = root
                         }).Where(c => c.TermoConsulta == pCanal.TermoConsulta).FirstOrDefault();

          if (canalBD == null)
          {
            var result = _youtubeAccesAPI.ConsultarCanal(pCanal.TermoConsulta);
            pCanal.CanalRoot = result;

            _Context.Canais.Add(pCanal);
            await _Context.SaveChangesAsync();

            return View(pCanal);
          }
          else
          {
            var itens = _Context.Item.Where(i => i.CanalRootID == canalBD.CanalRootID).Include(i => i.snippet).Include(i => i.id).Include(i => i.snippet.thumbnails).Include(i => i.snippet.thumbnails.high).ToListAsync().Result;
            canalBD.CanalRoot.items = itens;
            return View(canalBD);
          }          
        }
        else
        {
          return BadRequest("O termo de consulta não pode ser vazio");
        }
      }
      catch(Exception e)
      {
        return BadRequest(e.Message);
      }
    }
  }
}

ConsultarYoutubeAPI/Controllers/HomeController.cs
using ConsultarYoutubeAPI.Models;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ConsultarYoutubeAPI.Controllers
{
  public class HomeController : Controller
  {
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
      _logger = logger;
    }

    public IActionResult Index()
    {
      return View();
    }

    public IActionResult Privacy()
    {
      return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
      return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
  }
}

ConsultarYoutubeAPI/Controllers/VideoController.cs
using Common.Youtube;

using Dommain.Entidades.VideoHost;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using Repository;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ConsultarYoutubeAPI.Controllers
{
  public class VideoController : Controller
  {
    private readonly IYoutubeAccesAPI _youtubeAccesAPI;
    private readonly Context _Context;

    public VideoController(IYoutubeAccesAPI youtubeAccesAPI, Context pContext)
    {
      _youtubeAccesAPI = youtubeAccesAPI;
      _Context = pContext;
    }
    // GET: VideoController
    public ActionResult Index()
    {
      return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Index(ConsultaVideo pVideo)
    {
      try
      {
        if (ModelState.IsValid)
        {
          var VideoBD = (from c in _Context.Set<ConsultaVideo>()
                         join root in _Context.Set<VideoRoot>()
                         on c.VideoRootID equals root.ID
                         select new ConsultaVideo()
                         {
                           ID = c.ID,
                           TermoConsulta = c.TermoConsulta,
                           VideoRootID = c.VideoRootID,
                           VideoRoot = root
                         }).Where(c => c.TermoConsulta == pVideo.TermoConsulta).FirstOrDefault();

          if (VideoBD == null)
          {
            var result = _youtubeAccesAPI.ConsultarVideo(pVideo.TermoConsulta);
            pVideo.VideoRoot = result;

            _Context.Videos.Add(pVideo);
            await _Context.SaveChangesAsync();

            return View(pVideo);
          }
          else
          {
            var itens = _Context.Item.Where(i => i.VideoRootID == VideoBD.VideoRootID).Include(i => i.snippet).Include(i => i.id).Include(i => i.snippet.thumbnails).Include(i => i.snippet.thumbnails.high).ToListAsync().Result;
            VideoBD.VideoRoot.items = itens;
            return View(VideoBD);
          }
        }
        else
        {
          return BadRequest("O termo de consulta não pode ser vazio");
        }
      }
      catch (Exception e)
      {
        return BadRequest(e.Message);
      }
    }

  }
}

ConsultarYoutubeAPI/Views/Canal/Index.cshtml
@*
    Index CANAL
*@
@{
}
@model Dommain.Entidades.CanalHost.ConsultaCanal

@{
    ViewData["Title"] = "Consultar Canal";
}

<h1>Consultar Canal</h1>

<div class="row">
    <div class="col-md-6">
        <form asp-controller="Canal" asp-action="Index">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="TermoConsulta" class="form-control" id="search" />
                <span asp-validation-for="TermoConsulta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input class="btn btn-primary" value="Pesquisar" type="submit" />
            </div>
        </form>
    </div>
</div>

<div class="row margin-rodape content-center">
    @if (Model != null)
    {
        @if (Model.CanalRoot != null)
        {
            @foreach (var item in Model.CanalRoot.items)
            {

                <div class="col-md-4 div-cartao-previa margin-esquerda">
                    <img src="@item.snippet.thumbnails.high.url" width="320" />
                    <h5>@item.snippet.title</h5>
                    <label>@item.snippet.description</label>
                    <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#modalDetalhes" _titulo="@item.snippet.title" _descricao="@item.snippet.description" _publicacao="@item.snippet.publishedAt" id="@item.id.channelId" onclick="AbrirModal(id)">
                        Detalhes
                    </button>
                </div>
                <br />
            }
        }
    }
</div>

<!-- Modal -->
<div class="modal fade" id="modalDetalhes" tabindex="-1" aria-labelledby="modalDetalhes" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="h5exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h6>Descrição </h6> 
                <p id="modalDescricao"></p>
                <h6>Data Publicação </h6> 
                <p id="modalPublicacao"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script src="~/js/canalAbrirModal.js" defer></script>
}

ConsultarYoutubeAPI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo</h1>
    <img src="https://logodownload.org/wp-content/uploads/2014/10/youtube-logo-5-2.png" width="320" />
    <h2 class="display-4">Youtube Consulta</h2>
</div>

ConsultarYoutubeAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Consultar-Youtube</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Consultar - Youtube</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Canal" asp-action="Index">Canal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Video" asp-action="Index">Video</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Consultar Youtube
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ConsultarYoutubeAPI/Views/Video/Index.cshtml
@*
    Index VIDEO
*@
@{
}
@model Dommain.Entidades.VideoHost.ConsultaVideo

@{
    ViewData["Title"] = "Consultar Video";
}

<h1>Consultar Video</h1>

<div class="row">
    <div class="col-md-6">
        <form asp-controller="Video" asp-action="Index">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="TermoConsulta" class="form-control" id="search" />
                <span asp-validation-for="TermoConsulta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input class="btn btn-primary" value="Pesquisar" type="submit" />
            </div>
        </form>
    </div>
</div>

<div class="row margin-rodape content-center">
    @if (Model != null)
    {
        @if (Model.VideoRoot != null)
        {
            @foreach (var item in Model.VideoRoot.items)
            {

                <div class="col-md-4 div-cartao-previa margin-esquerda">
                    <img src="@item.snippet.thumbnails.high.url" width="320" />
                    <label>@item.snippet.title</label>
                    <label>@item.snippet.description</label>
                    <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#modalDetalhes" _titulo="@item.snippet.title" _descricao="@item.snippet.description" _publicacao="@item.snippet.publishedAt" id="@item.id.videoId" onclick="AbrirModal(id)">
                        Detalhes
                    </button>
                </div>
                <br />
            }
        }
    }
</div>

<!-- Modal -->
<div class="modal fade" id="modalDetalhes" tabindex="-1" aria-labelledby="modalDetalhes" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="h5exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h6>Descrição </h6>
                <p id="modalDescricao"></p>
                <h6>Data Publicação </h6>
                <p id="modalPublicacao"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script src="~/js/videoAbrirModal.js" defer></script>
}